name: 'Verify PHP code'
description: 'Checks the code quality with different tools'
runs:
  using: "composit"
  steps:
    - name: phpstan
      run: tools/phpstan analyse --memory-limit=512M --no-progress --no-interaction || true

    - name: phpcs
      run: |
        if [ -f tools/phpcs ]; then
            PHPCS_BIN=tools/phpcs
        elif [ -f vendor/bin/phpcs ]; then
            PHPCS_BIN=vendor/bin/phpcs
        else
            echo "phpcs not found"
            exit 1
        fi
        $PHPCS_BIN --colors --report=full

    - name: phpcs_compatibilitycheck
      run: |
        if [ -f tools/phpcs ]; then
        PHPCS_BIN=tools/phpcs
        elif [ -f vendor/bin/phpcs ]; then
            PHPCS_BIN=vendor/bin/phpcs
        else
            echo "phpcs not found"
            exit 1
        fi
        $PHPCS_BIN --standard=./phpcs.compatibilitycheck.xml --colors --report=full

    - name: phplint
      run: tools/phplint --no-progress

    - name: phpunit
      run: |
        export XDEBUG_MODE=coverage
        tools/phpunit.phar -c phpunit.xml --log-junit var/log/phpunit-test-report.xml --coverage-cobertura phpunit-coverage.xml --coverage-text --colors=never

    - name: composer_audit
      run: composer audit

    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODE_COV_TOKEN }}
        files: ./var/log/clover/clover.xml
        verbose: true
