name: 'Install PHP build envirnment'
description: 'Install Composer and Phive'
runs:
  using: "composit"
  steps:

    - name: "Cache tools installed with PHIVE"
      uses: "actions/cache@v3"
      with:
        path: "${{ runner.temp }}/.phive"
        key: "php-phive-${{ hashFiles('.phive/phars.xml') }}"
        restore-keys: "php-phive-"

    - name: "Install PHIVE"
        uses: "szepeviktor/phive@v1"
        with:
        home: "${{ runner.temp }}/.phive"
        binPath: "/usr/local/bin/phive"

    - name: Cache Composer dependencies
        uses: actions/cache@v3
        env:
        PHIVE_HOME: "${{ runner.temp }}/.phive"
        with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock', '**/composer.json') }}

      # composer install is already executed by php-actions/composer@v6 but in composer.json post-install-cmd can be defined.
      # But these are only executed if a composer.lock exists.
      # See https://getcomposer.org/doc/articles/scripts.md#command-events
      # For libraries the composer.lock is not checked in and is not present at the first composer install call.
      # Then only with the second composer install call also the post-install-cmd are executed.
      - name: composer_install
        env:
        PHIVE_HOME: "${{ runner.temp }}/.phive"
        run: |
        sudo chown -R $UID:$UID vendor
        composer --no-interaction global config --no-plugins allow-plugins.sitepark/composer-project true
        composer --no-interaction global require --dev "sitepark/composer-project:dev-main"
        composer validate
        composer install
