name: Composer Release

on: workflow_call

jobs:
  verify:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'ci(release):') }}

    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflow/actions/php-build-environment.yml
      - uses: ./.github/workflow/actions/php-verify.yml
