name: Composer Verify

on: workflow_call

jobs:
  verify:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'ci(release):') }}

    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: "Cache tools installed with PHIVE"
        uses: "actions/cache@v2.1.2"
        with:
          path: "${{ runner.temp }}/.phive"
          key: "php-phive-${{ hashFiles('.phive/phars.xml') }}"
          restore-keys: "php-phive-"

      - name: "Install PHIVE"
        uses: "szepeviktor/phive@v1"
        with:
          home: "${{ runner.temp }}/.phive"
          binPath: "/usr/local/bin/phive"
  
      - uses: php-actions/composer@v6

      # composer install is already executed by php-actions/composer@v6 but in composer.json post-install-cmd can be defined.
      # But these are only executed if a composer.lock exists.
      # See https://getcomposer.org/doc/articles/scripts.md#command-events
      # For libraries the composer.lock is not checked in and is not present at the first composer install call.
      # Then only with the second composer install call also the post-install-cmd are executed.
      - name: composer_install
        run: |
          ls -la
          id
          env
          sudo chown -R $UID:$UID vendor
          composer install

      - name: phpstan
        run: tools/phpstan analyse --memory-limit=512M --no-progress --no-interaction || true

      - name: phpcs
        run: |
          if [ -f tools/phpcs ]; then
            PHPCS_BIN=tools/phpcs
          elif [ -f vendor/bin/phpcs ]; then
            PHPCS_BIN=vendor/bin/phpcs
          else
            echo "phpcs not found"
            exit 1
          fi
          mkdir target
          $PHPCS_BIN --colors --report=full

      - name: phplint
        run: tools/phplint --no-progress

      - name: phpunit
        run: |
          export XDEBUG_MODE=coverage
          tools/phpunit.phar -c phpunit.xml --log-junit var/log/phpunit-test-report.xml --coverage-cobertura phpunit-coverage.xml --coverage-text --colors=never

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          files: ./var/log/clover/clover.xml
          verbose: true
