#
# Creates a hotfix branch by passing a tag reference.
# From this the version is determined and a branch
# `hotfix/[major][minor].x` is created. If the tag
# already exists and the `pom.xml` contains a
# `SNAPSHOT` version, the hotfix is considered as
# already started.
#
# Example:
#
# name: Start Maven Hotfix
# on: workflow_dispatch
#
# jobs:
#  start-hotfix:
#    uses: sitepark/project-workflow/.github/workflows/maven-start-hotfix.yml@main
#    with:
#      ref: ${{ github.ref }}
#
#

name: Maven Start Hotfix

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  start-hotfix:

    if: ${{ startsWith(inputs.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest

    steps:
      - name: Parse version from ref
        id: get-version
        run: |
          version=$(echo ${{inputs.ref}} | cut -d/ -f3)
          echo "::set-output name=version::$version"

      - name: Parse semver string
        uses: madhead/semver-utils@latest
        id: semver
        with:
           version: ${{ steps.get-version.outputs.version }}

      - name: Checkout release
        uses: actions/checkout@v3
        with:
           ref: ${{inputs.ref}}

      - name: Create hotifx branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           branch: "hotfix/${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}.x"

      - name: Checkout hotifx branch
        uses: actions/checkout@v3
        with:
           ref: hotfix/${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}.x

      - name: Extract version from pom.xml
        id: extract_gav
        uses: andreacomo/maven-gav-extractor@v1

      - name: Check if hotfix already started
        if: ${{ endsWith(steps.extract_gav.outputs.version, '-SNAPSHOT') }}
        run: |
            echo "Hotfix already started. Current hotfix version is ${{ steps.extract_gav.outputs.version }}"
            exit 1


      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Set next hotfix version
        run: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${{ steps.semver.outputs.inc-patch }}-SNAPSHOT

      - name: Commit pom.xml
        uses: EndBug/add-and-commit@v9
        with:
           message: "ci(release): set next hotfix version"




