name: Publish Maven Release

on:
  workflow_call:
    secrets:
      MVN_REPO_SERVER_USERNAME:
        required: true
      MVN_REPO_SERVER_PASSWORD:
        required: true
      MVN_REPO_SERVER_ID:
        required: true
      MVN_REPO_SERVER_SNAPSHOT_URL:
        required: true

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get project-version from pom.xml
        id: get-project-version
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: "pom.xml"
          xpath: '//*[local-name()="project"]/*[local-name()="version"]'

      - name: Check if snapshot
        if: ${{ endsWith(steps.get-project-version.outputs.info, '-SNAPSHOT') == true }}
        run: |
          echo "A snapshot-version: ${{ steps.get-project-version.outputs.info }}"
          exit 1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "11" # nexus-staging:release needs java 11
          distribution: "adopt"
          cache: "maven"

      - name: Setup settings.xml
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: '[{"id": "${{ secrets.MVN_REPO_SERVER_ID }}", "username": "${{ secrets.MVN_REPO_SERVER_USERNAME }}", "password": "${{ secrets.MVN_REPO_SERVER_PASSWORD }}"}]'
          repositories: '[{"id":"${{ secrets.MVN_REPO_SERVER_ID }}","name":"${{ secrets.MVN_REPO_SERVER_ID }}","url":"${{ secrets.MVN_REPO_SERVER_RELEASE_URL }}","snapshots":{"enabled":false}}]'

      - name: Publish Release
        run: |
          cat ~/.m2/settings.xml
          mvn --activate-profiles=nexus-staging-release --batch-mode nexus-staging:release
        env:
          MAVEN_USERNAME: ${{ secrets.MVN_REPO_SERVER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MVN_REPO_SERVER_PASSWORD }}
