name: Publish Maven Release

on: workflow_call

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Publish Maven Artifact
        run:
           echo "Manually publish from staging repository https://s01.oss.sonatype.org/#stagingRepositories"
           'echo "TODO: https://central.sonatype.org/publish/publish-maven/#nexus-staging-maven-plugin-for-deployment-and-release"'
